"""Add users table

Revision ID: ac2553153560
Revises: 
Create Date: 2024-12-23 16:51:41.926294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'ac2553153560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='dbo'
    )
    op.drop_table('Profession')
    op.drop_table('PolygonCoordinates')
    op.drop_table('PersonDetails')
    op.drop_table('LandPolygons')
    op.drop_table('sysdiagrams')
    op.drop_table('Polygons')
    op.drop_table('LandAreas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LandAreas',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Latitude', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('Longitude', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK__LandArea__3214EC0774839D18')
    )
    op.create_table('Polygons',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Area', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK__Polygons__3214EC074BF5F8E4')
    )
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B61DB3BFB24')
    )
    op.create_table('LandPolygons',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('PolygonData', sa.NullType(), autoincrement=False, nullable=False),
    sa.Column('Description', sa.NVARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Id', name='PK__LandPoly__3214EC07B29CEFD5')
    )
    op.create_table('PersonDetails',
    sa.Column('PersonID', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('FullName', sa.NVARCHAR(length=100, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('DateOfBirth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('Address', sa.NVARCHAR(length=200, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('PhoneNumber', sa.NVARCHAR(length=15, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('Salary', sa.DECIMAL(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('ProfessionId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('PersonID', name='PK__PersonDe__AA2FFB85F9873775')
    )
    op.create_table('PolygonCoordinates',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('PolygonId', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Latitude', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.Column('Longitude', sa.FLOAT(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['PolygonId'], ['Polygons.Id'], name='FK__PolygonCo__Polyg__267ABA7A'),
    sa.PrimaryKeyConstraint('Id', name='PK__PolygonC__3214EC07A404D6B5')
    )
    op.create_table('Profession',
    sa.Column('Id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.NVARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('Id', name='PK__Professi__3214EC079B821FFA')
    )
    op.drop_table('users', schema='dbo')
    # ### end Alembic commands ###
